CREATE TABLE ORDERS (
  ID INT PRIMARY KEY AUTO_INCREMENT
);

CREATE TABLE ORDER_ITEMS (
  ID INT PRIMARY KEY AUTO_INCREMENT,
  ORDER_ID INT NOT NULL,
  FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ID)
);